### ISSUE TITLE
Remove UI widget objects attached to core data classes

### ISSUE THREAD

**Issue by flv0** [iar74/jdfn#4]
./datamodel/DfnNode.java:119:    public Object _visual; // @todo FIXME!
./datamodel/DfnEdge.java:80:    public Object _visual; // @todo FIXME!
./datamodel/DfnPort.java:82:    public Object _visual; // @todo FIXME!

Ok so what's the concept again?

[Haha I just see there's of course a user named todo, which will always be notified if someone posts anything containing @todo. bad luck I would say. @todo: sorry! :smile:]

**Comment by flv0** [comment]
Closing. We might consider removing the github jdfn repos altogether in order to avoid duplication / confusion.

**Comment by iar74** [comment]
Absolutely.
